default_stages: [pre-commit]
repos:
  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.0.4
    hooks:
      - id: pylint
        args:
          - --disable=all
          - --enable=access-member-before-definition
          - --enable=bad-open-mode
          - --enable=deprecated-module
          - --enable=function-redefined
          - --enable=no-self-argument
          - --enable=undefined-variable
          - --enable=used-before-assignment
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [textual, types-requests]
  # - repo: local
  #   hooks:
  #     - id: no-commit-to-main
  #       name: Prevent commits to main
  #       entry: bash
  #       args: ['-c', 'if [ "$(git rev-parse --abbrev-ref HEAD)" = "main" ]; then echo "‚ùå ERROR: Direct commits to main branch are not allowed! Please create a feature branch first."; exit 1; fi']
  #       language: system
  #       pass_filenames: false
  #       always_run: true
